// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcnPvVgyct24YJHRx_kBCJ1Ed__TJC48c',
    appId: '1:1001143278741:web:5d38da0e9d0117e5a58f9c',
    messagingSenderId: '1001143278741',
    projectId: 'chat-app-38a98',
    authDomain: 'chat-app-38a98.firebaseapp.com',
    databaseURL: 'https://chat-app-38a98-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-38a98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGYQkrj-D8RzsmYAWfbJ3A94rWGW-XOc',
    appId: '1:1001143278741:android:f5be7c663f023af4a58f9c',
    messagingSenderId: '1001143278741',
    projectId: 'chat-app-38a98',
    databaseURL: 'https://chat-app-38a98-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-38a98.firebasestorage.app',
  );
}
